# Generated by Django 5.0.4 on 2024-05-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0029_remove_projectmember_invited_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/projects/covers/"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/users/avatars/"
            ),
        ),
    ]
