# Generated by Django 5.0.4 on 2024-05-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0030_alter_project_cover_alter_user_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
