# Generated by Django 5.0.4 on 2024-05-27 11:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0031_remove_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Priority",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=124)),
                ("color", models.CharField(default="#33cc33", max_length=10)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="priorities",
                        to="taskite.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Priority",
                "verbose_name_plural": "Priorities",
                "db_table": "priorities",
            },
        ),
        migrations.AddConstraint(
            model_name="priority",
            constraint=models.UniqueConstraint(
                fields=("project_id", "name"), name="unique_project_priority_name"
            ),
        ),
    ]
