# Generated by Django 5.0.4 on 2024-05-27 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0032_priority_priority_unique_project_priority_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="priority",
            new_name="priority_depr",
        ),
    ]
