# Generated by Django 5.0.4 on 2024-05-27 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0033_rename_priority_task_priority_depr"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="taskite.priority",
            ),
        ),
    ]
