# Generated by Django 5.0.4 on 2024-05-28 17:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskite", "0035_taskattachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resource",
                    models.FileField(
                        upload_to="", verbose_name="uploads/tasks/attachments/"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="taskite.task",
                    ),
                ),
            ],
            options={
                "db_table": "attachments",
            },
        ),
        migrations.DeleteModel(
            name="TaskAttachment",
        ),
    ]
